command:
  - "uvicorn"
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: SERVING_ENDPOINT_NAME
    valueFrom: serving-endpoint
  - name: PGHOST
    valueFrom: postgres
  - name: PGDATABASE
    valueFrom: postgres
  - name: PGUSER
    valueFrom: postgres
  - name: PGPORT
    valueFrom: postgres
  - name: PGSSLMODE
    valueFrom: postgres
